### ISSUE TITLE
Add the request context and logger to all public methods in server/channels/app/authentication.go

### ISSUE THREAD

**Issue by noxer** [mattermost/mattermost#21566]
#### Summary
To improve logging, we want to replace the global logger with a request specific one (which will add the request ID to the log message). The request context therefore contains a logger which is already pre-configured with the appropriate information. The task remains to pass the context to all methods used in fulfilling the request.

#### Tasks
- [ ] Change all public methods in `server/channels/app/authentication.go` to receive `rctx request.CTX` as the first argument [1].
- [ ] Change all methods in `server/channels/app/authentication.go` (even private ones) that use the `mlog` logger to use receive the context as well.
- [ ] Make sure all functions calling the changed methods pass along the context.
- [ ] Update the generated interfaces with `make generated`.
- [ ] Update the tests.

[1] Only if they have an `*App` receiver: `func (a *App) MethodName()`, others like `func (s *Server) ...` should be skipped. It they call a method you've changed, you should of course add the parameter as required.

#### Hints
- There changes tend to change a lot of files. Don't be afraid to ask for guidance when you feel it's getting out of control. Since a lot of these methods call each other it's common to have to change 10 or more files.
- Some methods already contain a `c *request.Context`. You can replace it with `rctx request.CTX`. `request.Context` implements the interface `request.CTX` so there should be no problem passing a `*Context` to a `CTX` parameter.
- Some methods may have references from the plugin API. Don't change the method signature there! The plugin API contains a preconfigured context for this purpose (`api.ctx`).
- The tests often work with a "TestHelper" (`th`) struct which contains a `th.Context`. If it's missing you can use a test helper from another package for ideas on how to add it.
- Most of the time you just need to regenerate the interface `AppIface`. `make app-layers` generates just this one interface and is generally faster than `make generated`.
- `api4` has it's own, separate context struct. That context contains the `request.CTX` we need. You can use `c.AppContext` to pass it to `App` methods.
- https://github.com/mattermost/mattermost/pull/24859 can be used as an example.

**Comment by iam-hitesh** [comment]
Hi @noxer,

I want to pick this issue.

**Comment by iam-hitesh** [comment]
Hi @noxer,

I added a PR(#21644 ) for above issue, please find here: https://github.com/mattermost/mattermost-server/pull/21644

**Comment by Kimbohlovette** [comment]
Hello @hanzei, please can I work on this?

**Comment by hanzei** [comment]
Sure, @Kimbohlovette. Please let me know if you have any questions

**Comment by Kimbohlovette** [comment]
Hello @hanzei,
Please how do I run backend test?
