### ISSUE TITLE
Add Request Context and logger to all public methods in server/channels/app/analytics.go

### ISSUE THREAD

**Issue by noxer** [mattermost/mattermost#21564]
#### Summary
To improve logging, we want to replace the global logger with a request specific one (which will add the request ID to the log message). The request context therefore contains a logger which is already pre-configured with the appropriate information. The task remains to pass the context to all methods used in fulfilling the request.

#### Tasks
- [ ] Change all public methods in `server/channels/app/analytics.go` to receive `rctx request.CTX` as the first argument [1].
- [ ] Change all methods in `server/channels/app/analytics.go` (even private ones) that use the `mlog` logger to use receive the context as well.
- [ ] Make sure all functions calling the changed methods pass along the context.
- [ ] Update the generated interfaces with `make generated`.
- [ ] Update the tests.

[1] Only if they have an `*App` receiver: `func (a *App) MethodName()`, others like `func (s *Server) ...` should be skipped. It they call a method you've changed, you should of course add the parameter as required.

#### Hints
- There changes tend to change a lot of files. Don't be afraid to ask for guidance when you feel it's getting out of control. Since a lot of these methods call each other it's common to have to change 10 or more files.
- Some methods already contain a `c *request.Context`. You can replace it with `rctx request.CTX`. `request.Context` implements the interface `request.CTX` so there should be no problem passing a `*Context` to a `CTX` parameter.
- Some methods may have references from the plugin API. Don't change the method signature there! The plugin API contains a preconfigured context for this purpose (`api.ctx`).
- The tests often work with a "TestHelper" (`th`) struct which contains a `th.Context`. If it's missing you can use a test helper from another package for ideas on how to add it.
- Most of the time you just need to regenerate the interface `AppIface`. `make app-layers` generates just this one interface and is generally faster than `make generated`.
- `api4` has it's own, separate context struct. That context contains the `request.CTX` we need. You can use `c.AppContext` to pass it to `App` methods.
- https://github.com/mattermost/mattermost/pull/24859 can be used as an example.

**Comment by svbnbyrk** [comment]
Would you assign it to me?

**Comment by nydhy** [comment]
Hey @noxer @amyblais 
I'd like to pick this up. Please assign it to me.

**Comment by noxer** [comment]
Sure @nydhy , thanks for tackling this.

**Comment by nydhy** [comment]
@noxer I've a few questions. 
- As per the tasklist, we have to pass this request.CTX to (a *App) methods only. But in app/analytics.go, there are only 4 such methods. 
- In another point it has been mentioned that we need to include all public methods in the file. Does that mean the public methods that have been called in this file or the public methods created in this file? 
- If it is the former, do we need to add CTX to all the chained methods like Srv(), Store(), User() or just end methods like Count() ? [Please refer the attached image]
![image](https://user-images.githubusercontent.com/43001338/221422840-f6df669c-a0bf-4d9b-ad2c-bfb96b2573ea.png)

**Comment by noxer** [comment]
Hi @nydhy, unfortunately I'm no longer with Mattermost. Maybe @agnivade can help you here.

**Comment by agnivade** [comment]
1. Yes there are just 4 methods. That's fine.
2. For now, only the 4 methods should be okay.

**Comment by hanzei** [comment]
@nydhy Please let me know if you still want to work on this ticket.

**Comment by nitintf** [comment]
Hi there! I'm interested in picking up this issue. Could you assign it to me? Thanks!

**Comment by nitintf** [comment]
Hey there are in total 4 methods in that file but only one uses `mlog` do i still need to pass the `rtcx` to other methods which are not doing any logging

**Comment by hanzei** [comment]
All public methods should get an `rctx` as the first argument.

**Comment by hanzei** [comment]
@nitintf Is there anything else I can help you with?

**Comment by nitintf** [comment]
Hey, I hope you're doing well. So, about the GitHub ticket you assigned to me – turns out I won't be able to handle it due to some unexpected hurdles that cropped up. Apologies for the inconvenience. Could you possibly reassign it to someone else who's available to jump in. THANKS

**Comment by hanzei** [comment]
All good, thanks for the heads up @nitintf  :+1:

**Comment by kaashmonee** [comment]
Hi @hanzei, I'd be really interested in this! May I be assigned to work on it?

**Comment by hanzei** [comment]
Sure @kaashmonee

**Comment by hanzei** [comment]
@kaashmonee Please let me know if you have any questions.

**Comment by apshada** [comment]
@hanzei I would like to take this issue

**Comment by hanzei** [comment]
@apshada Is there anything I can help you with?

**Comment by apshada** [comment]
@hanzei I am working on it

**Comment by hanzei** [comment]
Awesome, looking forward to your PR 🚀
