### ISSUE TITLE
Add the request context and logger to all public methods in server/channels/app/audit.go

### ISSUE THREAD

**Issue by noxer** [mattermost/mattermost#21565]
#### Summary
To improve logging, we want to replace the global logger with a request specific one (which will add the request ID to the log message). The request context therefore contains a logger which is already pre-configured with the appropriate information. The task remains to pass the context to all methods used in fulfilling the request.

#### Tasks
- [ ] Change all public methods in `server/channels/app/audit.go` to receive `rctx request.CTX` as the first argument [1].
- [ ] Change all methods in `server/channels/app/audit.go` (even private ones) that use the `mlog` logger to use receive the context as well.
- [ ] Make sure all functions calling the changed methods pass along the context.
- [ ] Update the generated interfaces with `make generated`.
- [ ] Update the tests.

[1] Only if they have an `*App` receiver: `func (a *App) MethodName()`, others like `func (s *Server) ...` should be skipped. It they call a method you've changed, you should of course add the parameter as required.

#### Hints
- There changes tend to change a lot of files. Don't be afraid to ask for guidance when you feel it's getting out of control. Since a lot of these methods call each other it's common to have to change 10 or more files.
- Some methods already contain a `c *request.Context`. You can replace it with `rctx request.CTX`. `request.Context` implements the interface `request.CTX` so there should be no problem passing a `*Context` to a `CTX` parameter.
- Some methods may have references from the plugin API. Don't change the method signature there! The plugin API contains a preconfigured context for this purpose (`api.ctx`).
- The tests often work with a "TestHelper" (`th`) struct which contains a `th.Context`. If it's missing you can use a test helper from another package for ideas on how to add it.
- Most of the time, you just need to regenerate the interface `AppIface`. `make app-layers` generates just this one interface and is generally faster than `make generated`.
- `api4` has its own, separate context struct. That context contains the `request.CTX` we need. You can use `c.AppContext` to pass it to `App` methods.
- https://github.com/mattermost/mattermost/pull/24859 can be used as an example.

**Comment by stelgkio** [comment]
I would like to take this.

**Comment by abhinav700** [comment]
@hanzei I would Like to work on this issue. Can you please assign this to me

**Comment by hanzei** [comment]
Thank you @abhinav700 👍

**Comment by abhinav700** [comment]
@hanzei I think that the issue description and title should be changed.

It looks like there has been some change in the directory structure of the mattermost, and the app folder no longer resides at the root level.

**Comment by hanzei** [comment]
Good catch @abhinav700 :+1:  I've updated the issue

**Comment by hanzei** [comment]
Making this ticket available again per the request of @abhinav700

**Comment by Kimbohlovette** [comment]
Hello @hanzei can I work on this one?

**Comment by hanzei** [comment]
Sure @Kimbohlovette :+1:

**Comment by Kimbohlovette** [comment]
Hello @hanzei, I opened a PR #25368 on this issue. Please take a look at it. Check out the *Note* section. Thanks

**Comment by hanzei** [comment]
Thanks @Kimbohlovette , I will your PR later today
