### ISSUE TITLE
Add the request context to all public methods in server/channels/app/brand.go

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost#25495]
### Summary

To improve logging, we want to replace the global logger with a request-specific one (which will add the request ID to the log message). The request context therefore contains a logger already preconfigured with the appropriate information. The task remains to pass the context to all methods used in fulfilling the request.

#### Tasks
- [ ] Change all public methods in `server/channels/app/brand.go` to receive `rctx request.CTX` as the first argument [1].
- [ ] Change all methods in `server/channels/app/brand.go` (even private ones) that use the `mlog` logger to receive the context as well. The methods to look for are `mlog.Debug`,`mlog.Info`, `mlog.Warn`, `mlog.Error`.
- [ ] Make sure all functions calling the changed methods pass along the context.
- [ ] Update the generated interfaces with `make generated`.
- [ ] Update the tests.

[1] Only if they have an `*App` receiver: `func (a *App) MethodName()`, others like `func (s *Server) ...` should be skipped. If they call a method you've changed, you should - of course - add the parameter as required.

#### Hints
- These changes tend to change a lot of files. Don't be afraid to ask for guidance when you feel it's getting out of control. Since a lot of these methods call each other, it's common to have to change 10 or more files.
- Some methods already contain a `c *request.Context`. You can replace it with `rctx request.CTX`. `request.Context` implements the interface `request.CTX`, so there should be no problem passing a `*Context` to a `CTX` parameter.
- Some methods may have references from the plugin API. Don't change the method signature there! The plugin API contains a preconfigured context for this purpose (`api.ctx`).
- The tests often work with a "TestHelper" (`th') struct, which contains a `th.Context`. If it's missing, you can use a test helper from another package for ideas on how to add it.
- Most of the time, you just need to regenerate the interface `AppIface`. `make app-layers` generates just this one interface and is generally faster than `make generated`.
- `api4` has its own, separate context struct. That context contains the `request.CTX` we need. You can use `c.AppContext` to pass it to `App` methods.
- In tests, the `request.CTX` of `TestHelper` should be used, if available. If no context is available, use `request.TestContext` to create one.
- https://github.com/mattermost/mattermost/pull/24859 can be used as an example.

~~------~~

If you have any questions, please reach out to @hanzei or @fmartingr either on this ticket or on [the Mattermost Community server>(https://community.mattermost.com).

**Comment by AvaterClasher** [comment]
Can i take this ?

**Comment by AvaterClasher** [comment]
@hanzei i think this is bit out of my league sorry 🥲

**Comment by hanzei** [comment]
No worries. Let me know if there is still anything I can help you with.

**Comment by sudheer121** [comment]
hey @hanzei, thanks for the detailed summary, I can take this up 😃
