### ISSUE TITLE
Fix errcheck issues in server/channels/api4/bot_test.go

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost#28331]
At Mattermost, we are committed to maintaining a high standard of code quality, reliability, and security. To further enhance this, we are launching a community campaign to integrate the [`errcheck`](https://github.com/kisielk/errcheck) linter across the Mattermost codebase.

This Help Wanted ticket is about fixing the linter issues reported by `errcheck` in `channels/api4/bot_test.go`.

### What is `errcheck`?

`errcheck` is a tool that automatically identifies places in Go code where errors are returned but not checked. In Go, error handling is a critical part of writing robust applications, and ignoring returned errors can lead to bugs, crashes, or unintended behavior. By integrating `errcheck` into the codebase, we can ensure that error handling is consistently and properly managed across the project.

### Tasks
- [ ] Remove the expection for `channels/api4/bot_test.go` from exections list for `errcheck` in `server/.golangci.yml`.
- [ ] Run `make golangci-lint` to get a list of all linter errors.
- [ ] Fix the error by properly handling them.
- [ ] Run `make golangci-lint` again to ensure that all errors are fixed.

#### Okay, but what does "properly handling" mean?

In general, errors should be returned to the caller. Non critical errors should be loggged and function execution should continue.

In tests, errors should be checked using `assert.NoError(t, err)` for errors of type `error` or `assert.Nil(t, err)` for errors of type `**model.AppError`.
If an error is expected, it should be checked using `assert.Error(t, err)` for errors of type `error` or `assert.NotNil(t, err)` for errors of type `**model.AppError`.

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on the Mattermost Community server, where you can discuss questions with community members and the Mattermost core team.
For technical advice or questions, please [join our "Developers Server" community channel](https://community.mattermost.com/core/channels/developers-server).
You can also reach out to @hanzei either on this ticket or on [the Mattermost Community server](https://community.mattermost.com).

For new contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: MM-60691

**Comment by Aryakoste** [comment]
Hello @hanzei I would like to work on this issue.

**Comment by hanzei** [comment]
Awesome, thank you @Aryakoste

**Comment by Aryakoste** [comment]
https://github.com/mattermost/mattermost/pull/28329 This pull request when merged will list ignored files for errcheck linter. From there i can remove bot_test.go. So should i add this list in my yml or wait for this PR to merge.

**Comment by Aryakoste** [comment]
@hanzei

**Comment by Aryakoste** [comment]
Or i will make this change temporary in my local and will make changes.

**Comment by hanzei** [comment]
Let's wait for https://github.com/mattermost/mattermost/pull/28329 to be merged before we merge your changes. Feel free to copy the changes from https://github.com/mattermost/mattermost/pull/28329 into your branch.

**Comment by hanzei** [comment]
@Aryakoste https://github.com/mattermost/mattermost/pull/28329 is merged
